package com.yanyue.rag.domain.agent.budget;

public enum BudgetDimension {
    REQUEST_ANALYSIS_CALL,
    PRIMARY_DEEP_READ_CALL,
    REPAIR_DEEP_READ_CALL,
    EVIDENCE_JUDGE_CALL,
    FINAL_ANSWER_CALL,
    GENERATIVE_LLM_LOGICAL_CALL,
    GENERATIVE_LLM_PHYSICAL_ATTEMPT,
    GENERATIVE_LLM_INPUT_TOKEN,
    GENERATIVE_LLM_OUTPUT_TOKEN,
    PHYSICAL_SEARCH,
    SEMANTIC_EMBEDDING_OPERATION,
    RERANK_CALL,
    PARENT_READ,
    CANDIDATE_SPAN_OFFERED,
    ACCEPTED_EVIDENCE,
    FINAL_REFERENCE,
    SERIAL_SEMANTIC_STAGE
}
